// Offline support. Bump VERSION whenever app files change so players get the update.
const VERSION = 'bastion-v13';

const APP_SHELL = [
  './',
  './index.html',
  './styles.css',
  './manifest.webmanifest',
  './icons/icon-192.png',
  './icons/icon-512.png',
  './assets/models/Textures/colormap.png',
  './assets/models/castle/Textures/colormap.png',
  './assets/models/castle/flag-banner-long.glb',
  './assets/models/castle/flag-pennant.glb',
  './assets/models/castle/flag-wide.glb',
  './assets/models/castle/flag.glb',
  './assets/models/castle/gate.glb',
  './assets/models/castle/ground-hills.glb',
  './assets/models/castle/rocks-small.glb',
  './assets/models/castle/stairs-stone.glb',
  './assets/models/castle/tower-base.glb',
  './assets/models/castle/tower-hexagon-base.glb',
  './assets/models/castle/tower-hexagon-mid.glb',
  './assets/models/castle/tower-hexagon-roof.glb',
  './assets/models/castle/tower-hexagon-top.glb',
  './assets/models/castle/tower-square-base.glb',
  './assets/models/castle/tower-square-mid-door.glb',
  './assets/models/castle/tower-square-mid-windows.glb',
  './assets/models/castle/tower-square-mid.glb',
  './assets/models/castle/tower-square-top-roof-high-windows.glb',
  './assets/models/castle/tower-square-top-roof-high.glb',
  './assets/models/castle/tower-square-top-roof.glb',
  './assets/models/castle/tower-top.glb',
  './assets/models/castle/wall-corner.glb',
  './assets/models/castle/wall-doorway.glb',
  './assets/models/castle/wall-half.glb',
  './assets/models/castle/wall-narrow-wood-fence.glb',
  './assets/models/castle/wall-narrow-wood.glb',
  './assets/models/castle/wall-narrow.glb',
  './assets/models/castle/wall-pillar.glb',
  './assets/models/castle/wall.glb',
  './assets/models/characters/Textures/colormap.png',
  './assets/models/characters/character-female-b.glb',
  './assets/models/characters/character-female-d.glb',
  './assets/models/characters/character-female-f.glb',
  './assets/models/characters/character-male-a.glb',
  './assets/models/characters/character-male-c.glb',
  './assets/models/characters/character-male-e.glb',
  './assets/models/detail-crystal-large.glb',
  './assets/models/detail-crystal.glb',
  './assets/models/detail-rocks-large.glb',
  './assets/models/detail-rocks.glb',
  './assets/models/detail-tree-large.glb',
  './assets/models/detail-tree.glb',
  './assets/models/enemy-ufo-a.glb',
  './assets/models/enemy-ufo-b.glb',
  './assets/models/enemy-ufo-beam.glb',
  './assets/models/enemy-ufo-c-weapon.glb',
  './assets/models/enemy-ufo-c.glb',
  './assets/models/enemy-ufo-d.glb',
  './assets/models/nature/flower_purpleA.glb',
  './assets/models/nature/flower_redA.glb',
  './assets/models/nature/flower_redB.glb',
  './assets/models/nature/flower_yellowA.glb',
  './assets/models/nature/flower_yellowB.glb',
  './assets/models/nature/grass_large.glb',
  './assets/models/nature/grass_leafs.glb',
  './assets/models/nature/log_stack.glb',
  './assets/models/nature/mushroom_redGroup.glb',
  './assets/models/nature/mushroom_tanGroup.glb',
  './assets/models/nature/plant_bush.glb',
  './assets/models/nature/plant_bushDetailed.glb',
  './assets/models/nature/plant_bushLarge.glb',
  './assets/models/nature/plant_bushSmall.glb',
  './assets/models/nature/rock_smallA.glb',
  './assets/models/nature/rock_smallC.glb',
  './assets/models/nature/rock_smallFlatA.glb',
  './assets/models/nature/rock_tallA.glb',
  './assets/models/nature/stump_round.glb',
  './assets/models/nature/tree_cone.glb',
  './assets/models/nature/tree_default.glb',
  './assets/models/nature/tree_default_fall.glb',
  './assets/models/nature/tree_detailed.glb',
  './assets/models/nature/tree_fat.glb',
  './assets/models/nature/tree_oak.glb',
  './assets/models/nature/tree_oak_fall.glb',
  './assets/models/nature/tree_pineRoundA.glb',
  './assets/models/nature/tree_pineRoundC.glb',
  './assets/models/selection-a.glb',
  './assets/models/snow-detail-crystal.glb',
  './assets/models/snow-detail-rocks-large.glb',
  './assets/models/snow-detail-rocks.glb',
  './assets/models/snow-detail-tree-large.glb',
  './assets/models/snow-detail-tree.glb',
  './assets/models/snow-tile-corner-round.glb',
  './assets/models/snow-tile-crystal.glb',
  './assets/models/snow-tile-end-round.glb',
  './assets/models/snow-tile-hill.glb',
  './assets/models/snow-tile-rock.glb',
  './assets/models/snow-tile-spawn-end.glb',
  './assets/models/snow-tile-straight.glb',
  './assets/models/snow-tile-tree-double.glb',
  './assets/models/snow-tile-tree-quad.glb',
  './assets/models/snow-tile-tree.glb',
  './assets/models/snow-tile.glb',
  './assets/models/spawn-round.glb',
  './assets/models/survival/Textures/colormap.png',
  './assets/models/survival/barrel.glb',
  './assets/models/survival/box-large.glb',
  './assets/models/survival/box.glb',
  './assets/models/survival/chest.glb',
  './assets/models/survival/fence-fortified.glb',
  './assets/models/survival/resource-planks.glb',
  './assets/models/survival/resource-stone.glb',
  './assets/models/survival/resource-wood.glb',
  './assets/models/survival/rock-a.glb',
  './assets/models/survival/rock-b.glb',
  './assets/models/survival/rock-c.glb',
  './assets/models/survival/rock-flat.glb',
  './assets/models/survival/structure-roof.glb',
  './assets/models/survival/structure.glb',
  './assets/models/survival/tool-axe.glb',
  './assets/models/survival/tool-hammer.glb',
  './assets/models/survival/tool-pickaxe.glb',
  './assets/models/survival/tree-autumn.glb',
  './assets/models/survival/tree-tall.glb',
  './assets/models/survival/tree-trunk.glb',
  './assets/models/survival/tree.glb',
  './assets/models/survival/workbench-anvil.glb',
  './assets/models/tile-corner-round.glb',
  './assets/models/tile-crystal.glb',
  './assets/models/tile-end-round.glb',
  './assets/models/tile-hill.glb',
  './assets/models/tile-rock.glb',
  './assets/models/tile-spawn-end.glb',
  './assets/models/tile-straight.glb',
  './assets/models/tile-tree-double.glb',
  './assets/models/tile-tree-quad.glb',
  './assets/models/tile-tree.glb',
  './assets/models/tile.glb',
  './assets/models/tower-round-bottom-a.glb',
  './assets/models/tower-round-bottom-b.glb',
  './assets/models/tower-round-bottom-c.glb',
  './assets/models/tower-round-build-a.glb',
  './assets/models/tower-round-build-b.glb',
  './assets/models/tower-round-build-c.glb',
  './assets/models/tower-round-build-d.glb',
  './assets/models/tower-round-build-f.glb',
  './assets/models/tower-round-crystals.glb',
  './assets/models/tower-round-middle-a.glb',
  './assets/models/tower-round-middle-b.glb',
  './assets/models/tower-round-middle-c.glb',
  './assets/models/tower-round-roof-a.glb',
  './assets/models/tower-round-top-a.glb',
  './assets/models/tower-round-top-b.glb',
  './assets/models/tower-round-top-c.glb',
  './assets/models/tower-square-bottom-a.glb',
  './assets/models/tower-square-bottom-b.glb',
  './assets/models/tower-square-bottom-c.glb',
  './assets/models/tower-square-build-a.glb',
  './assets/models/tower-square-build-b.glb',
  './assets/models/tower-square-build-c.glb',
  './assets/models/tower-square-build-d.glb',
  './assets/models/tower-square-build-e.glb',
  './assets/models/tower-square-build-f.glb',
  './assets/models/tower-square-middle-a.glb',
  './assets/models/tower-square-middle-b.glb',
  './assets/models/tower-square-middle-c.glb',
  './assets/models/tower-square-roof-a.glb',
  './assets/models/tower-square-roof-b.glb',
  './assets/models/tower-square-roof-c.glb',
  './assets/models/tower-square-top-a.glb',
  './assets/models/tower-square-top-b.glb',
  './assets/models/tower-square-top-c.glb',
  './assets/models/town/Textures/colormap.png',
  './assets/models/town/banner-green.glb',
  './assets/models/town/banner-red.glb',
  './assets/models/town/cart.glb',
  './assets/models/town/chimney.glb',
  './assets/models/town/fence.glb',
  './assets/models/town/fountain-round.glb',
  './assets/models/town/hedge.glb',
  './assets/models/town/lantern.glb',
  './assets/models/town/overhang.glb',
  './assets/models/town/planks.glb',
  './assets/models/town/poles.glb',
  './assets/models/town/roof-gable.glb',
  './assets/models/town/roof-high-gable.glb',
  './assets/models/town/roof-high-point.glb',
  './assets/models/town/roof-point.glb',
  './assets/models/town/stall-green.glb',
  './assets/models/town/stall-red.glb',
  './assets/models/town/wall-door.glb',
  './assets/models/town/wall-window-glass.glb',
  './assets/models/town/wall-window-shutters.glb',
  './assets/models/town/wall-window-small.glb',
  './assets/models/town/wall-wood-door.glb',
  './assets/models/town/wall-wood-window-shutters.glb',
  './assets/models/town/wall-wood-window-small.glb',
  './assets/models/town/wall-wood.glb',
  './assets/models/town/wall.glb',
  './assets/models/town/wheel.glb',
  './assets/models/town/windmill.glb',
  './assets/models/weapon-ammo-arrow.glb',
  './assets/models/weapon-ammo-boulder.glb',
  './assets/models/weapon-ammo-bullet.glb',
  './assets/models/weapon-ammo-cannonball.glb',
  './assets/models/weapon-ballista.glb',
  './assets/models/weapon-cannon.glb',
  './assets/models/weapon-catapult.glb',
  './assets/models/weapon-turret.glb',
  './src/audio/audio.js',
  './src/config.js',
  './src/core/cloud.js',
  './src/core/loop.js',
  './src/core/math.js',
  './src/core/random.js',
  './src/core/storage.js',
  './src/data/achievements.js',
  './src/data/enemies.js',
  './src/data/levels.js',
  './src/data/objectives.js',
  './src/data/perks.js',
  './src/data/realm.js',
  './src/data/spells.js',
  './src/data/themes.js',
  './src/data/towers.js',
  './src/data/waves.js',
  './src/game/game.js',
  './src/game/realmHud.js',
  './src/game/realmMode.js',
  './src/input/pointer.js',
  './src/main.js',
  './src/render/ambient.js',
  './src/render/assets.js',
  './src/render/cameraRig.js',
  './src/render/effects.js',
  './src/render/enemyViews.js',
  './src/render/particles.js',
  './src/render/projectileViews.js',
  './src/render/realmTerrain.js',
  './src/render/realmViews.js',
  './src/render/spellViews.js',
  './src/render/thumbnails.js',
  './src/render/towerViews.js',
  './src/render/view.js',
  './src/render/world.js',
  './src/sim/level.js',
  './src/sim/realm.js',
  './src/sim/simulation.js',
  './src/ui/haptics.js',
  './src/ui/ui.js',
  './vendor/three/build/three.core.js',
  './vendor/three/build/three.module.js',
  './vendor/three/examples/jsm/loaders/GLTFLoader.js',
  './vendor/three/examples/jsm/math/SimplexNoise.js',
  './vendor/three/examples/jsm/postprocessing/EffectComposer.js',
  './vendor/three/examples/jsm/postprocessing/GTAOPass.js',
  './vendor/three/examples/jsm/postprocessing/MaskPass.js',
  './vendor/three/examples/jsm/postprocessing/OutputPass.js',
  './vendor/three/examples/jsm/postprocessing/Pass.js',
  './vendor/three/examples/jsm/postprocessing/RenderPass.js',
  './vendor/three/examples/jsm/postprocessing/ShaderPass.js',
  './vendor/three/examples/jsm/postprocessing/UnrealBloomPass.js',
  './vendor/three/examples/jsm/shaders/CopyShader.js',
  './vendor/three/examples/jsm/shaders/GTAOShader.js',
  './vendor/three/examples/jsm/shaders/LuminosityHighPassShader.js',
  './vendor/three/examples/jsm/shaders/OutputShader.js',
  './vendor/three/examples/jsm/shaders/PoissonDenoiseShader.js',
  './vendor/three/examples/jsm/utils/BufferGeometryUtils.js',
  './vendor/three/examples/jsm/utils/SkeletonUtils.js',
];


self.addEventListener('install', (event) => {
  event.waitUntil(
    (async () => {
      const cache = await caches.open(VERSION);
      // cache: 'reload' skips the browser's HTTP cache (GitHub Pages keeps files 10 min),
      // so a new version never stores stale copies of the previous one.
      await cache.addAll(APP_SHELL.map((url) => new Request(url, { cache: 'reload' })));
      await self.skipWaiting();
    })(),
  );
});

self.addEventListener('activate', (event) => {
  event.waitUntil(
    (async () => {
      const keys = await caches.keys();
      await Promise.all(keys.filter((key) => key !== VERSION).map((key) => caches.delete(key)));
      await self.clients.claim();
    })(),
  );
});

// Everything is served from the cache first: the game starts instantly and works with no
// network (or a bad one). Updates come from a new sw.js (new VERSION), which the browser
// checks on each launch; the page reloads into the new version from the menu.
async function fromCache(request) {
  const cache = await caches.open(VERSION);
  const cached = await cache.match(request, { ignoreSearch: true });
  if (cached) return cached;
  try {
    const response = await fetch(request, { cache: 'no-cache' });
    if (response.ok) cache.put(request, response.clone());
    return response;
  } catch (error) {
    if (request.mode === 'navigate') {
      const page = (await cache.match('./')) ?? (await cache.match('./index.html'));
      if (page) return page;
    }
    throw error;
  }
}

async function fonts(request) {
  const cache = await caches.open(VERSION);
  const cached = await cache.match(request);
  if (cached) return cached;
  const response = await fetch(request);
  if (response.ok || response.type === 'opaque') cache.put(request, response.clone());
  return response;
}

self.addEventListener('fetch', (event) => {
  const { request } = event;
  if (request.method !== 'GET') return;
  const url = new URL(request.url);
  if (url.origin === self.location.origin) event.respondWith(fromCache(request));
  else if (url.hostname === 'fonts.googleapis.com' || url.hostname === 'fonts.gstatic.com') event.respondWith(fonts(request));
});
