// Packs the item icons rendered by items.py into one WebP sprite sheet and writes the
// matching index (src/ui/itemArt.js).
//
//   npm i sharp
//   node atlas.mjs <icons dir> <out.webp> <out.js> [tile px] [--preview=<sheet.png>]
import fs from 'fs';
import path from 'path';
import sharp from 'sharp';

const [dir, outImage, outIndex, tileArg] = process.argv.slice(2);
const preview = process.argv.find((a) => a.startsWith('--preview='))?.slice(10);
const TILE = Number(tileArg) || 160;
const order = JSON.parse(fs.readFileSync(path.join(dir, 'order.json'), 'utf8'));
const COLS = 6;
const ROWS = Math.ceil(order.length / COLS);
const tiles = await Promise.all(order.map((id) => sharp(path.join(dir, `${id}.png`)).resize(TILE, TILE, { kernel: 'lanczos3' }).toBuffer()));
const composite = tiles.map((input, i) => ({ input, left: (i % COLS) * TILE, top: Math.floor(i / COLS) * TILE }));
const sheet = () => sharp({ create: { width: COLS * TILE, height: ROWS * TILE, channels: 4, background: { r: 0, g: 0, b: 0, alpha: 0 } } }).composite(composite);
await sheet().webp({ quality: 86, alphaQuality: 90, effort: 6 }).toFile(outImage);
if (preview) {
  await sharp({ create: { width: COLS * TILE, height: ROWS * TILE, channels: 4, background: '#1c2240' } }).composite(composite).png().toFile(preview);
}
fs.writeFileSync(outIndex, `// Generated by tools/blender/atlas.mjs: where each item's picture sits in
// assets/icons/items.webp (rendered in Blender by tools/blender/items.py).
export const ITEM_ART = { cols: ${COLS}, rows: ${ROWS}, ids: ${JSON.stringify(order)} };
`);
console.log(`${order.length} icons, ${COLS}×${ROWS} × ${TILE}px, ${(fs.statSync(outImage).size / 1024).toFixed(0)} KB`);
