// Generated by tools/blender/atlas.mjs: where each item's picture sits in
// assets/icons/items.webp (rendered in Blender by tools/blender/items.py).
export const ITEM_ART = { cols: 6, rows: 4, ids: ["bow","crossbow","staff","blades","longbow","shuriken","tome","leather","mail","robe","shadowgarb","wolf","bear","serpent","falcon","life","rage","fortune","fang","bat","owl","frostling","salamander"] };
